const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_10_35_10_17_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI0LFxuICAgICAgICA2OSxcbiAgICAgICAgOTAsXG4gICAgICAgIDc4LFxuICAgICAgICAyMDksXG4gICAgICAgIDExMixcbiAgICAgICAgMTQ4LFxuICAgICAgICAyNDYsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMzksXG4gICAgICAgIDgyLFxuICAgICAgICA1LFxuICAgICAgICAxMjksXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTYwLFxuICAgICAgICAxMDgsXG4gICAgICAgIDU4LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTM2LFxuICAgICAgICAyMzksXG4gICAgICAgIDc5LFxuICAgICAgICA3NCxcbiAgICAgICAgODUsXG4gICAgICAgIDE2NCxcbiAgICAgICAgOTgsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTksXG4gICAgICAgIDg0LFxuICAgICAgICA2OSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMDJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA2LFxuICAgICAgICAxOTYsXG4gICAgICAgIDQ2LFxuICAgICAgICAyNixcbiAgICAgICAgMTE4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDM4LFxuICAgICAgICAxNzcsXG4gICAgICAgIDIwMyxcbiAgICAgICAgNzMsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMzUsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTQsXG4gICAgICAgIDY3LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMzMsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNTUsXG4gICAgICAgIDU1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTgyLFxuICAgICAgICAyMDIsXG4gICAgICAgIDU2LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTg4LFxuICAgICAgICA5MFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICAxNDEsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMixcbiAgICAgICAgMjIsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTcwLFxuICAgICAgICAyNDAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMzYsXG4gICAgICAgIDksXG4gICAgICAgIDMyLFxuICAgICAgICAxMjksXG4gICAgICAgIDUzLFxuICAgICAgICA1MixcbiAgICAgICAgMTg2LFxuICAgICAgICA1NCxcbiAgICAgICAgNjgsXG4gICAgICAgIDM4LFxuICAgICAgICAyMixcbiAgICAgICAgMTMxLFxuICAgICAgICAxNDEsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTYxLFxuICAgICAgICAyMCxcbiAgICAgICAgMTIyLFxuICAgICAgICAxOTAsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTE2LFxuICAgICAgICAxNyxcbiAgICAgICAgODVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDY0LFxuICAgICAgICAxMDMsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTYyLFxuICAgICAgICAyNyxcbiAgICAgICAgMTc4LFxuICAgICAgICAxLFxuICAgICAgICAyMjQsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTEzLFxuICAgICAgICAxNjMsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTI3LFxuICAgICAgICA0NSxcbiAgICAgICAgNDIsXG4gICAgICAgIDMwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTE5LFxuICAgICAgICAxNzgsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTgzLFxuICAgICAgICAxMDEsXG4gICAgICAgIDczLFxuICAgICAgICAyMzIsXG4gICAgICAgIDI4LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTAxLFxuICAgICAgICA0NSxcbiAgICAgICAgMzhcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE5MixcbiAgICAgICAgMTg0LFxuICAgICAgICAxMTUsXG4gICAgICAgIDQwLFxuICAgICAgICAxNTMsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjEyLFxuICAgICAgICA3NyxcbiAgICAgICAgNTMsXG4gICAgICAgIDg1LFxuICAgICAgICA1NCxcbiAgICAgICAgMTkyLFxuICAgICAgICA3NixcbiAgICAgICAgNjYsXG4gICAgICAgIDE5LFxuICAgICAgICA4MSxcbiAgICAgICAgMjEyLFxuICAgICAgICAxMTYsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTY4LFxuICAgICAgICA3MixcbiAgICAgICAgMjAxLFxuICAgICAgICAxMTMsXG4gICAgICAgIDE3OSxcbiAgICAgICAgNTgsXG4gICAgICAgIDkzLFxuICAgICAgICAxOTMsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMzksXG4gICAgICAgIDIyLFxuICAgICAgICA1NSxcbiAgICAgICAgMTI1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEwNSxcbiAgICAgICAgODMsXG4gICAgICAgIDExNSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMzIsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTU0LFxuICAgICAgICA5MSxcbiAgICAgICAgMTY3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIzMixcbiAgICAgICAgODEsXG4gICAgICAgIDI0LFxuICAgICAgICAyNTEsXG4gICAgICAgIDUzLFxuICAgICAgICAzOSxcbiAgICAgICAgNTEsXG4gICAgICAgIDE5NCxcbiAgICAgICAgNDMsXG4gICAgICAgIDE2MixcbiAgICAgICAgMjM3LFxuICAgICAgICAzOSxcbiAgICAgICAgMTUxLFxuICAgICAgICA5LFxuICAgICAgICAxMDQsXG4gICAgICAgIDI3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMzcsXG4gICAgICAgIDY4LFxuICAgICAgICAxMTksXG4gICAgICAgIDEyNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA1NixcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICA3NyxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDEyNlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgOSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDU0XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICAzOSxcbiAgICAgICAgMzQsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTE2LFxuICAgICAgICA2MixcbiAgICAgICAgMTgsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMTEsXG4gICAgICAgIDIyLFxuICAgICAgICAxMSxcbiAgICAgICAgMTYyLFxuICAgICAgICAxMCxcbiAgICAgICAgMTI1LFxuICAgICAgICA1OSxcbiAgICAgICAgMTcsXG4gICAgICAgIDgxLFxuICAgICAgICAxMDIsXG4gICAgICAgIDMxLFxuICAgICAgICAyMTYsXG4gICAgICAgIDExNyxcbiAgICAgICAgMzUsXG4gICAgICAgIDEwMyxcbiAgICAgICAgNTksXG4gICAgICAgIDIyMCxcbiAgICAgICAgOTAsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjUxLFxuICAgICAgICAzNixcbiAgICAgICAgMzIsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjEsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTEwLFxuICAgICAgICAyMjEsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTY2LFxuICAgICAgICA3MixcbiAgICAgICAgMTQwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDg3LFxuICAgICAgICAxOTYsXG4gICAgICAgIDg1LFxuICAgICAgICA3OSxcbiAgICAgICAgMTgsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMyxcbiAgICAgICAgMjEyLFxuICAgICAgICAxOTgsXG4gICAgICAgIDY0LFxuICAgICAgICA1NSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNDcsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTcsXG4gICAgICAgIDEwOSxcbiAgICAgICAgNDcsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTY0LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTI0LFxuICAgICAgICA0XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxMzEsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiUElMYVRCemwyeWNCVkxIcDRtR1cxZXk1ektlUStoankxSW9IQnNObm9scz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjM0MjI4MDgzMTFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjI2NjY4NzBEODBGODUwMjY2M0Q2MjQ5MDRFQjFBRTk1XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyOTE2MTMxOVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzQyMjgwODMxMUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNjc2RkEyMjU3MUE2RkVBRkQwN0IwOTM5OEE3QTg2RjFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI5MTYxMzIyXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIndJaHA0UlBNUVhPTmJQM1daZE84N2dcIixcbiAgXCJwaG9uZUlkXCI6IFwiMGY2ZmM4ZDktNmE5MS00Y2ZhLWE1NGQtMThiMzU0NTMxYzZkXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE5MSxcbiAgICAgIDE2NSxcbiAgICAgIDIyNSxcbiAgICAgIDE0MyxcbiAgICAgIDE5LFxuICAgICAgMTEwLFxuICAgICAgMTYzLFxuICAgICAgMTgzLFxuICAgICAgMTQ4LFxuICAgICAgMTU5LFxuICAgICAgMTU1LFxuICAgICAgMzgsXG4gICAgICA2LFxuICAgICAgMjQxLFxuICAgICAgODQsXG4gICAgICA3NSxcbiAgICAgIDE3NSxcbiAgICAgIDIzNyxcbiAgICAgIDI1NCxcbiAgICAgIDI0M1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxOTMsXG4gICAgICA3NCxcbiAgICAgIDE0NCxcbiAgICAgIDE4NCxcbiAgICAgIDE3MCxcbiAgICAgIDE1LFxuICAgICAgMSxcbiAgICAgIDIzOCxcbiAgICAgIDIzNixcbiAgICAgIDI0OCxcbiAgICAgIDUxLFxuICAgICAgMTE4LFxuICAgICAgMjQ0LFxuICAgICAgMTkxLFxuICAgICAgNzAsXG4gICAgICAxNzIsXG4gICAgICAxNTYsXG4gICAgICAyNTMsXG4gICAgICAxNSxcbiAgICAgIDI0M1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJOQkw4RjdTU1wiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzNDIyODA4MzExOjU4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxODY2OTQwOTE0Njg5MjU6NThAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiQ2ggQXNhZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0t6anIrWUZFTi9RdzdnR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiTTY1SDdlNGZ5WDE1TnhPUGtBbE1zU0Rvb2pEWVdHUmVKZWxvRDFzTzhDRT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJRS1cyN2VFRkduaDg2aytxVmpOWXEvdDhpU2FEemUxcmJIMGRUSElyM2piYlFGN1pHZ2hsY2ROQmc1djJCOVhoMVpRS0p0TkF6M1krN2prQlZJY0lEUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJVbVkyK0dNWSs0WVIrVmcveXNMa2RaQlBxSnFtaUcwTEV0bzQ1TStnV2VYZy91WU5YNFhIK1A5Ni9ES1I2RWRROGdNVGg1SmgrQnQvMzNJYXRqSzVEQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjM0MjI4MDgzMTE6NThAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDksXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAzM1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI5MTYxMzE1LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSXZqXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJdmouanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJaZHJjVmk5TWFUTE5Zc1h1N2hVM28vaHowSzBDQjd5RHltTkJQL1dTT3ZrPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1NTY4Njk1NDcsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
